package mihon.sync.transport.api

import mihon.sync.core.model.Changeset

interface SyncTransport {
    /**
     * Pushes a changeset produced locally to the transport medium.
     */
    suspend fun push(changeset: Changeset)

    /**
     * Pulls changesets from the transport medium that were produced since [sinceCursors] per remote device,
     * ignoring changesets generated by [excludeDeviceId].
     */
    suspend fun pull(
        sinceCursors: Map<String, Long> = emptyMap(),
        excludeDeviceId: String? = null,
    ): List<Changeset>

    /**
     * Convenience overload for pulling changesets with a single cursor fallback.
     */
    suspend fun pull(
        sinceCursor: Long,
        excludeDeviceId: String? = null,
    ): List<Changeset> = pull(emptyMap(), excludeDeviceId)

    /**
     * Returns the highest cursor observed on the transport medium across remote devices,
     * or 0 if no remote changesets exist.
     */
    suspend fun headCursor(excludeDeviceId: String? = null): Long
}
